[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"
description = ""
license = ""

[lib]
crate-type = ["staticlib"]

[dependencies]
zephyr = "0.1"

oskey-action = { path = "lib/core/action", default-features = false, features = [
  "crypto-psa",
] }

anyhow = { version = "1.0", default-features = false }
zeroize = { version = "1.9", default-features = false, features = ["alloc"] }

[build-dependencies]
cbindgen = "0.29"

[profile.release]
strip = true
opt-level = 'z'
lto = "thin"
panic = 'abort'
