# Debug
CONFIG_DEBUG_COREDUMP=n

# CONFIG_ISR_STACK_SIZE=1024
CONFIG_HEAP_MEM_POOL_SIZE=32768

# Stack
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y

# UART
CONFIG_UART_INTERRUPT_DRIVEN=y

# Entropy
CONFIG_ENTROPY_GENERATOR=y

# Device
CONFIG_HWINFO=y
CONFIG_REBOOT=y
