# SPDX-License-Identifier: MPL-2.0

SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="${APP_DIR}/sign/root-ec-p256.pem"
SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
